server:
  port: 8080

spring:
  application:
    name: eos-A
    
message: 'FROM CONFIGS-EDITED BY SARVESH*********'
encryptedProperty: '{cipher}43c8e4ef100fe97a84c29e5020cd194d92dc73debccd3f56716e39caeea3b679'
