server:
  port: 8080

spring:
  application:
    name: eos-A
    
message: 'FROM CONFIGS-EDITED BY SARVESH'
encryptedProperty: '{cipher}061c45346624bf26dbf7ba1ef2e622dcb8abfdfa376158a3046025a3305a9ea78'
